name: CASImaging
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-lightning
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - pip
  - jupyter
  - jupyterlab=2.*
  - jupyter_contrib_nbextensions
  - ipywidgets
  - seaborn
  - scikit-learn
  - captum
  - nodejs
  - pip:
    - albumentations
    - tqdm
    - opencv-python
    - psutil
    - jedi==0.17.2