name: CASImaging
channels:
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-lightning
  - numpy
  - matplotlib
  - scikit-image
  - pandas
  - pip
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - ipywidgets
  - seaborn
  - scikit-learn
  - plotly=4.14.1
  - plotly-orca
  - captum
  - pip:
    - tqdm
    - opencv-python
    - psutil